// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/api/servicecontrol/v1/distribution.proto

#include "google/api/servicecontrol/v1/distribution.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

namespace google {
namespace api {
namespace servicecontrol {
namespace v1 {
PROTOBUF_CONSTEXPR Distribution_LinearBuckets::Distribution_LinearBuckets(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.width_)*/0
  , /*decltype(_impl_.offset_)*/0
  , /*decltype(_impl_.num_finite_buckets_)*/0
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct Distribution_LinearBucketsDefaultTypeInternal {
  PROTOBUF_CONSTEXPR Distribution_LinearBucketsDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~Distribution_LinearBucketsDefaultTypeInternal() {}
  union {
    Distribution_LinearBuckets _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 Distribution_LinearBucketsDefaultTypeInternal _Distribution_LinearBuckets_default_instance_;
PROTOBUF_CONSTEXPR Distribution_ExponentialBuckets::Distribution_ExponentialBuckets(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.growth_factor_)*/0
  , /*decltype(_impl_.scale_)*/0
  , /*decltype(_impl_.num_finite_buckets_)*/0
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct Distribution_ExponentialBucketsDefaultTypeInternal {
  PROTOBUF_CONSTEXPR Distribution_ExponentialBucketsDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~Distribution_ExponentialBucketsDefaultTypeInternal() {}
  union {
    Distribution_ExponentialBuckets _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 Distribution_ExponentialBucketsDefaultTypeInternal _Distribution_ExponentialBuckets_default_instance_;
PROTOBUF_CONSTEXPR Distribution_ExplicitBuckets::Distribution_ExplicitBuckets(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.bounds_)*/{}
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct Distribution_ExplicitBucketsDefaultTypeInternal {
  PROTOBUF_CONSTEXPR Distribution_ExplicitBucketsDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~Distribution_ExplicitBucketsDefaultTypeInternal() {}
  union {
    Distribution_ExplicitBuckets _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 Distribution_ExplicitBucketsDefaultTypeInternal _Distribution_ExplicitBuckets_default_instance_;
PROTOBUF_CONSTEXPR Distribution::Distribution(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.bucket_counts_)*/{}
  , /*decltype(_impl_._bucket_counts_cached_byte_size_)*/{0}
  , /*decltype(_impl_.exemplars_)*/{}
  , /*decltype(_impl_.count_)*/int64_t{0}
  , /*decltype(_impl_.mean_)*/0
  , /*decltype(_impl_.minimum_)*/0
  , /*decltype(_impl_.maximum_)*/0
  , /*decltype(_impl_.sum_of_squared_deviation_)*/0
  , /*decltype(_impl_.bucket_option_)*/{}
  , /*decltype(_impl_._cached_size_)*/{}
  , /*decltype(_impl_._oneof_case_)*/{}} {}
struct DistributionDefaultTypeInternal {
  PROTOBUF_CONSTEXPR DistributionDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~DistributionDefaultTypeInternal() {}
  union {
    Distribution _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 DistributionDefaultTypeInternal _Distribution_default_instance_;
}  // namespace v1
}  // namespace servicecontrol
}  // namespace api
}  // namespace google
static ::_pb::Metadata file_level_metadata_google_2fapi_2fservicecontrol_2fv1_2fdistribution_2eproto[4];
static constexpr ::_pb::EnumDescriptor const** file_level_enum_descriptors_google_2fapi_2fservicecontrol_2fv1_2fdistribution_2eproto = nullptr;
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_google_2fapi_2fservicecontrol_2fv1_2fdistribution_2eproto = nullptr;

const uint32_t TableStruct_google_2fapi_2fservicecontrol_2fv1_2fdistribution_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::google::api::servicecontrol::v1::Distribution_LinearBuckets, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::google::api::servicecontrol::v1::Distribution_LinearBuckets, _impl_.num_finite_buckets_),
  PROTOBUF_FIELD_OFFSET(::google::api::servicecontrol::v1::Distribution_LinearBuckets, _impl_.width_),
  PROTOBUF_FIELD_OFFSET(::google::api::servicecontrol::v1::Distribution_LinearBuckets, _impl_.offset_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::google::api::servicecontrol::v1::Distribution_ExponentialBuckets, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::google::api::servicecontrol::v1::Distribution_ExponentialBuckets, _impl_.num_finite_buckets_),
  PROTOBUF_FIELD_OFFSET(::google::api::servicecontrol::v1::Distribution_ExponentialBuckets, _impl_.growth_factor_),
  PROTOBUF_FIELD_OFFSET(::google::api::servicecontrol::v1::Distribution_ExponentialBuckets, _impl_.scale_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::google::api::servicecontrol::v1::Distribution_ExplicitBuckets, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::google::api::servicecontrol::v1::Distribution_ExplicitBuckets, _impl_.bounds_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::google::api::servicecontrol::v1::Distribution, _internal_metadata_),
  ~0u,  // no _extensions_
  PROTOBUF_FIELD_OFFSET(::google::api::servicecontrol::v1::Distribution, _impl_._oneof_case_[0]),
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::google::api::servicecontrol::v1::Distribution, _impl_.count_),
  PROTOBUF_FIELD_OFFSET(::google::api::servicecontrol::v1::Distribution, _impl_.mean_),
  PROTOBUF_FIELD_OFFSET(::google::api::servicecontrol::v1::Distribution, _impl_.minimum_),
  PROTOBUF_FIELD_OFFSET(::google::api::servicecontrol::v1::Distribution, _impl_.maximum_),
  PROTOBUF_FIELD_OFFSET(::google::api::servicecontrol::v1::Distribution, _impl_.sum_of_squared_deviation_),
  PROTOBUF_FIELD_OFFSET(::google::api::servicecontrol::v1::Distribution, _impl_.bucket_counts_),
  ::_pbi::kInvalidFieldOffsetTag,
  ::_pbi::kInvalidFieldOffsetTag,
  ::_pbi::kInvalidFieldOffsetTag,
  PROTOBUF_FIELD_OFFSET(::google::api::servicecontrol::v1::Distribution, _impl_.exemplars_),
  PROTOBUF_FIELD_OFFSET(::google::api::servicecontrol::v1::Distribution, _impl_.bucket_option_),
};
static const ::_pbi::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, -1, sizeof(::google::api::servicecontrol::v1::Distribution_LinearBuckets)},
  { 9, -1, -1, sizeof(::google::api::servicecontrol::v1::Distribution_ExponentialBuckets)},
  { 18, -1, -1, sizeof(::google::api::servicecontrol::v1::Distribution_ExplicitBuckets)},
  { 25, -1, -1, sizeof(::google::api::servicecontrol::v1::Distribution)},
};

static const ::_pb::Message* const file_default_instances[] = {
  &::google::api::servicecontrol::v1::_Distribution_LinearBuckets_default_instance_._instance,
  &::google::api::servicecontrol::v1::_Distribution_ExponentialBuckets_default_instance_._instance,
  &::google::api::servicecontrol::v1::_Distribution_ExplicitBuckets_default_instance_._instance,
  &::google::api::servicecontrol::v1::_Distribution_default_instance_._instance,
};

const char descriptor_table_protodef_google_2fapi_2fservicecontrol_2fv1_2fdistribution_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n/google/api/servicecontrol/v1/distribut"
  "ion.proto\022\034google.api.servicecontrol.v1\032"
  "\035google/api/distribution.proto\"\236\005\n\014Distr"
  "ibution\022\r\n\005count\030\001 \001(\003\022\014\n\004mean\030\002 \001(\001\022\017\n\007"
  "minimum\030\003 \001(\001\022\017\n\007maximum\030\004 \001(\001\022 \n\030sum_of"
  "_squared_deviation\030\005 \001(\001\022\025\n\rbucket_count"
  "s\030\006 \003(\003\022R\n\016linear_buckets\030\007 \001(\01328.google"
  ".api.servicecontrol.v1.Distribution.Line"
  "arBucketsH\000\022\\\n\023exponential_buckets\030\010 \001(\013"
  "2=.google.api.servicecontrol.v1.Distribu"
  "tion.ExponentialBucketsH\000\022V\n\020explicit_bu"
  "ckets\030\t \001(\0132:.google.api.servicecontrol."
  "v1.Distribution.ExplicitBucketsH\000\0224\n\texe"
  "mplars\030\n \003(\0132!.google.api.Distribution.E"
  "xemplar\032J\n\rLinearBuckets\022\032\n\022num_finite_b"
  "uckets\030\001 \001(\005\022\r\n\005width\030\002 \001(\001\022\016\n\006offset\030\003 "
  "\001(\001\032V\n\022ExponentialBuckets\022\032\n\022num_finite_"
  "buckets\030\001 \001(\005\022\025\n\rgrowth_factor\030\002 \001(\001\022\r\n\005"
  "scale\030\003 \001(\001\032!\n\017ExplicitBuckets\022\016\n\006bounds"
  "\030\001 \003(\001B\017\n\rbucket_optionB\354\001\n com.google.a"
  "pi.servicecontrol.v1B\021DistributionProtoP"
  "\001ZJgoogle.golang.org/genproto/googleapis"
  "/api/servicecontrol/v1;servicecontrol\370\001\001"
  "\252\002\036Google.Cloud.ServiceControl.V1\312\002\036Goog"
  "le\\Cloud\\ServiceControl\\V1\352\002!Google::Clo"
  "ud::ServiceControl::V1b\006proto3"
  ;
static const ::_pbi::DescriptorTable* const descriptor_table_google_2fapi_2fservicecontrol_2fv1_2fdistribution_2eproto_deps[1] = {
  &::descriptor_table_google_2fapi_2fdistribution_2eproto,
};
static ::_pbi::once_flag descriptor_table_google_2fapi_2fservicecontrol_2fv1_2fdistribution_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_google_2fapi_2fservicecontrol_2fv1_2fdistribution_2eproto = {
    false, false, 1030, descriptor_table_protodef_google_2fapi_2fservicecontrol_2fv1_2fdistribution_2eproto,
    "google/api/servicecontrol/v1/distribution.proto",
    &descriptor_table_google_2fapi_2fservicecontrol_2fv1_2fdistribution_2eproto_once, descriptor_table_google_2fapi_2fservicecontrol_2fv1_2fdistribution_2eproto_deps, 1, 4,
    schemas, file_default_instances, TableStruct_google_2fapi_2fservicecontrol_2fv1_2fdistribution_2eproto::offsets,
    file_level_metadata_google_2fapi_2fservicecontrol_2fv1_2fdistribution_2eproto, file_level_enum_descriptors_google_2fapi_2fservicecontrol_2fv1_2fdistribution_2eproto,
    file_level_service_descriptors_google_2fapi_2fservicecontrol_2fv1_2fdistribution_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_google_2fapi_2fservicecontrol_2fv1_2fdistribution_2eproto_getter() {
  return &descriptor_table_google_2fapi_2fservicecontrol_2fv1_2fdistribution_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_google_2fapi_2fservicecontrol_2fv1_2fdistribution_2eproto(&descriptor_table_google_2fapi_2fservicecontrol_2fv1_2fdistribution_2eproto);
namespace google {
namespace api {
namespace servicecontrol {
namespace v1 {

// ===================================================================

class Distribution_LinearBuckets::_Internal {
 public:
};

Distribution_LinearBuckets::Distribution_LinearBuckets(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:google.api.servicecontrol.v1.Distribution.LinearBuckets)
}
Distribution_LinearBuckets::Distribution_LinearBuckets(const Distribution_LinearBuckets& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  Distribution_LinearBuckets* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.width_){}
    , decltype(_impl_.offset_){}
    , decltype(_impl_.num_finite_buckets_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::memcpy(&_impl_.width_, &from._impl_.width_,
    static_cast<size_t>(reinterpret_cast<char*>(&_impl_.num_finite_buckets_) -
    reinterpret_cast<char*>(&_impl_.width_)) + sizeof(_impl_.num_finite_buckets_));
  // @@protoc_insertion_point(copy_constructor:google.api.servicecontrol.v1.Distribution.LinearBuckets)
}

inline void Distribution_LinearBuckets::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.width_){0}
    , decltype(_impl_.offset_){0}
    , decltype(_impl_.num_finite_buckets_){0}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

Distribution_LinearBuckets::~Distribution_LinearBuckets() {
  // @@protoc_insertion_point(destructor:google.api.servicecontrol.v1.Distribution.LinearBuckets)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void Distribution_LinearBuckets::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
}

void Distribution_LinearBuckets::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void Distribution_LinearBuckets::Clear() {
// @@protoc_insertion_point(message_clear_start:google.api.servicecontrol.v1.Distribution.LinearBuckets)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::memset(&_impl_.width_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&_impl_.num_finite_buckets_) -
      reinterpret_cast<char*>(&_impl_.width_)) + sizeof(_impl_.num_finite_buckets_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* Distribution_LinearBuckets::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // int32 num_finite_buckets = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          _impl_.num_finite_buckets_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // double width = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 17)) {
          _impl_.width_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<double>(ptr);
          ptr += sizeof(double);
        } else
          goto handle_unusual;
        continue;
      // double offset = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 25)) {
          _impl_.offset_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<double>(ptr);
          ptr += sizeof(double);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* Distribution_LinearBuckets::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:google.api.servicecontrol.v1.Distribution.LinearBuckets)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // int32 num_finite_buckets = 1;
  if (this->_internal_num_finite_buckets() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(1, this->_internal_num_finite_buckets(), target);
  }

  // double width = 2;
  static_assert(sizeof(uint64_t) == sizeof(double), "Code assumes uint64_t and double are the same size.");
  double tmp_width = this->_internal_width();
  uint64_t raw_width;
  memcpy(&raw_width, &tmp_width, sizeof(tmp_width));
  if (raw_width != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteDoubleToArray(2, this->_internal_width(), target);
  }

  // double offset = 3;
  static_assert(sizeof(uint64_t) == sizeof(double), "Code assumes uint64_t and double are the same size.");
  double tmp_offset = this->_internal_offset();
  uint64_t raw_offset;
  memcpy(&raw_offset, &tmp_offset, sizeof(tmp_offset));
  if (raw_offset != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteDoubleToArray(3, this->_internal_offset(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:google.api.servicecontrol.v1.Distribution.LinearBuckets)
  return target;
}

size_t Distribution_LinearBuckets::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:google.api.servicecontrol.v1.Distribution.LinearBuckets)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // double width = 2;
  static_assert(sizeof(uint64_t) == sizeof(double), "Code assumes uint64_t and double are the same size.");
  double tmp_width = this->_internal_width();
  uint64_t raw_width;
  memcpy(&raw_width, &tmp_width, sizeof(tmp_width));
  if (raw_width != 0) {
    total_size += 1 + 8;
  }

  // double offset = 3;
  static_assert(sizeof(uint64_t) == sizeof(double), "Code assumes uint64_t and double are the same size.");
  double tmp_offset = this->_internal_offset();
  uint64_t raw_offset;
  memcpy(&raw_offset, &tmp_offset, sizeof(tmp_offset));
  if (raw_offset != 0) {
    total_size += 1 + 8;
  }

  // int32 num_finite_buckets = 1;
  if (this->_internal_num_finite_buckets() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_num_finite_buckets());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData Distribution_LinearBuckets::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    Distribution_LinearBuckets::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*Distribution_LinearBuckets::GetClassData() const { return &_class_data_; }


void Distribution_LinearBuckets::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<Distribution_LinearBuckets*>(&to_msg);
  auto& from = static_cast<const Distribution_LinearBuckets&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:google.api.servicecontrol.v1.Distribution.LinearBuckets)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  static_assert(sizeof(uint64_t) == sizeof(double), "Code assumes uint64_t and double are the same size.");
  double tmp_width = from._internal_width();
  uint64_t raw_width;
  memcpy(&raw_width, &tmp_width, sizeof(tmp_width));
  if (raw_width != 0) {
    _this->_internal_set_width(from._internal_width());
  }
  static_assert(sizeof(uint64_t) == sizeof(double), "Code assumes uint64_t and double are the same size.");
  double tmp_offset = from._internal_offset();
  uint64_t raw_offset;
  memcpy(&raw_offset, &tmp_offset, sizeof(tmp_offset));
  if (raw_offset != 0) {
    _this->_internal_set_offset(from._internal_offset());
  }
  if (from._internal_num_finite_buckets() != 0) {
    _this->_internal_set_num_finite_buckets(from._internal_num_finite_buckets());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void Distribution_LinearBuckets::CopyFrom(const Distribution_LinearBuckets& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:google.api.servicecontrol.v1.Distribution.LinearBuckets)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Distribution_LinearBuckets::IsInitialized() const {
  return true;
}

void Distribution_LinearBuckets::InternalSwap(Distribution_LinearBuckets* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(Distribution_LinearBuckets, _impl_.num_finite_buckets_)
      + sizeof(Distribution_LinearBuckets::_impl_.num_finite_buckets_)
      - PROTOBUF_FIELD_OFFSET(Distribution_LinearBuckets, _impl_.width_)>(
          reinterpret_cast<char*>(&_impl_.width_),
          reinterpret_cast<char*>(&other->_impl_.width_));
}

::PROTOBUF_NAMESPACE_ID::Metadata Distribution_LinearBuckets::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_google_2fapi_2fservicecontrol_2fv1_2fdistribution_2eproto_getter, &descriptor_table_google_2fapi_2fservicecontrol_2fv1_2fdistribution_2eproto_once,
      file_level_metadata_google_2fapi_2fservicecontrol_2fv1_2fdistribution_2eproto[0]);
}

// ===================================================================

class Distribution_ExponentialBuckets::_Internal {
 public:
};

Distribution_ExponentialBuckets::Distribution_ExponentialBuckets(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:google.api.servicecontrol.v1.Distribution.ExponentialBuckets)
}
Distribution_ExponentialBuckets::Distribution_ExponentialBuckets(const Distribution_ExponentialBuckets& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  Distribution_ExponentialBuckets* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.growth_factor_){}
    , decltype(_impl_.scale_){}
    , decltype(_impl_.num_finite_buckets_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::memcpy(&_impl_.growth_factor_, &from._impl_.growth_factor_,
    static_cast<size_t>(reinterpret_cast<char*>(&_impl_.num_finite_buckets_) -
    reinterpret_cast<char*>(&_impl_.growth_factor_)) + sizeof(_impl_.num_finite_buckets_));
  // @@protoc_insertion_point(copy_constructor:google.api.servicecontrol.v1.Distribution.ExponentialBuckets)
}

inline void Distribution_ExponentialBuckets::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.growth_factor_){0}
    , decltype(_impl_.scale_){0}
    , decltype(_impl_.num_finite_buckets_){0}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

Distribution_ExponentialBuckets::~Distribution_ExponentialBuckets() {
  // @@protoc_insertion_point(destructor:google.api.servicecontrol.v1.Distribution.ExponentialBuckets)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void Distribution_ExponentialBuckets::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
}

void Distribution_ExponentialBuckets::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void Distribution_ExponentialBuckets::Clear() {
// @@protoc_insertion_point(message_clear_start:google.api.servicecontrol.v1.Distribution.ExponentialBuckets)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::memset(&_impl_.growth_factor_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&_impl_.num_finite_buckets_) -
      reinterpret_cast<char*>(&_impl_.growth_factor_)) + sizeof(_impl_.num_finite_buckets_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* Distribution_ExponentialBuckets::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // int32 num_finite_buckets = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          _impl_.num_finite_buckets_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // double growth_factor = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 17)) {
          _impl_.growth_factor_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<double>(ptr);
          ptr += sizeof(double);
        } else
          goto handle_unusual;
        continue;
      // double scale = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 25)) {
          _impl_.scale_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<double>(ptr);
          ptr += sizeof(double);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* Distribution_ExponentialBuckets::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:google.api.servicecontrol.v1.Distribution.ExponentialBuckets)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // int32 num_finite_buckets = 1;
  if (this->_internal_num_finite_buckets() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(1, this->_internal_num_finite_buckets(), target);
  }

  // double growth_factor = 2;
  static_assert(sizeof(uint64_t) == sizeof(double), "Code assumes uint64_t and double are the same size.");
  double tmp_growth_factor = this->_internal_growth_factor();
  uint64_t raw_growth_factor;
  memcpy(&raw_growth_factor, &tmp_growth_factor, sizeof(tmp_growth_factor));
  if (raw_growth_factor != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteDoubleToArray(2, this->_internal_growth_factor(), target);
  }

  // double scale = 3;
  static_assert(sizeof(uint64_t) == sizeof(double), "Code assumes uint64_t and double are the same size.");
  double tmp_scale = this->_internal_scale();
  uint64_t raw_scale;
  memcpy(&raw_scale, &tmp_scale, sizeof(tmp_scale));
  if (raw_scale != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteDoubleToArray(3, this->_internal_scale(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:google.api.servicecontrol.v1.Distribution.ExponentialBuckets)
  return target;
}

size_t Distribution_ExponentialBuckets::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:google.api.servicecontrol.v1.Distribution.ExponentialBuckets)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // double growth_factor = 2;
  static_assert(sizeof(uint64_t) == sizeof(double), "Code assumes uint64_t and double are the same size.");
  double tmp_growth_factor = this->_internal_growth_factor();
  uint64_t raw_growth_factor;
  memcpy(&raw_growth_factor, &tmp_growth_factor, sizeof(tmp_growth_factor));
  if (raw_growth_factor != 0) {
    total_size += 1 + 8;
  }

  // double scale = 3;
  static_assert(sizeof(uint64_t) == sizeof(double), "Code assumes uint64_t and double are the same size.");
  double tmp_scale = this->_internal_scale();
  uint64_t raw_scale;
  memcpy(&raw_scale, &tmp_scale, sizeof(tmp_scale));
  if (raw_scale != 0) {
    total_size += 1 + 8;
  }

  // int32 num_finite_buckets = 1;
  if (this->_internal_num_finite_buckets() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_num_finite_buckets());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData Distribution_ExponentialBuckets::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    Distribution_ExponentialBuckets::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*Distribution_ExponentialBuckets::GetClassData() const { return &_class_data_; }


void Distribution_ExponentialBuckets::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<Distribution_ExponentialBuckets*>(&to_msg);
  auto& from = static_cast<const Distribution_ExponentialBuckets&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:google.api.servicecontrol.v1.Distribution.ExponentialBuckets)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  static_assert(sizeof(uint64_t) == sizeof(double), "Code assumes uint64_t and double are the same size.");
  double tmp_growth_factor = from._internal_growth_factor();
  uint64_t raw_growth_factor;
  memcpy(&raw_growth_factor, &tmp_growth_factor, sizeof(tmp_growth_factor));
  if (raw_growth_factor != 0) {
    _this->_internal_set_growth_factor(from._internal_growth_factor());
  }
  static_assert(sizeof(uint64_t) == sizeof(double), "Code assumes uint64_t and double are the same size.");
  double tmp_scale = from._internal_scale();
  uint64_t raw_scale;
  memcpy(&raw_scale, &tmp_scale, sizeof(tmp_scale));
  if (raw_scale != 0) {
    _this->_internal_set_scale(from._internal_scale());
  }
  if (from._internal_num_finite_buckets() != 0) {
    _this->_internal_set_num_finite_buckets(from._internal_num_finite_buckets());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void Distribution_ExponentialBuckets::CopyFrom(const Distribution_ExponentialBuckets& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:google.api.servicecontrol.v1.Distribution.ExponentialBuckets)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Distribution_ExponentialBuckets::IsInitialized() const {
  return true;
}

void Distribution_ExponentialBuckets::InternalSwap(Distribution_ExponentialBuckets* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(Distribution_ExponentialBuckets, _impl_.num_finite_buckets_)
      + sizeof(Distribution_ExponentialBuckets::_impl_.num_finite_buckets_)
      - PROTOBUF_FIELD_OFFSET(Distribution_ExponentialBuckets, _impl_.growth_factor_)>(
          reinterpret_cast<char*>(&_impl_.growth_factor_),
          reinterpret_cast<char*>(&other->_impl_.growth_factor_));
}

::PROTOBUF_NAMESPACE_ID::Metadata Distribution_ExponentialBuckets::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_google_2fapi_2fservicecontrol_2fv1_2fdistribution_2eproto_getter, &descriptor_table_google_2fapi_2fservicecontrol_2fv1_2fdistribution_2eproto_once,
      file_level_metadata_google_2fapi_2fservicecontrol_2fv1_2fdistribution_2eproto[1]);
}

// ===================================================================

class Distribution_ExplicitBuckets::_Internal {
 public:
};

Distribution_ExplicitBuckets::Distribution_ExplicitBuckets(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:google.api.servicecontrol.v1.Distribution.ExplicitBuckets)
}
Distribution_ExplicitBuckets::Distribution_ExplicitBuckets(const Distribution_ExplicitBuckets& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  Distribution_ExplicitBuckets* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.bounds_){from._impl_.bounds_}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:google.api.servicecontrol.v1.Distribution.ExplicitBuckets)
}

inline void Distribution_ExplicitBuckets::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.bounds_){arena}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

Distribution_ExplicitBuckets::~Distribution_ExplicitBuckets() {
  // @@protoc_insertion_point(destructor:google.api.servicecontrol.v1.Distribution.ExplicitBuckets)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void Distribution_ExplicitBuckets::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.bounds_.~RepeatedField();
}

void Distribution_ExplicitBuckets::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void Distribution_ExplicitBuckets::Clear() {
// @@protoc_insertion_point(message_clear_start:google.api.servicecontrol.v1.Distribution.ExplicitBuckets)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.bounds_.Clear();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* Distribution_ExplicitBuckets::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // repeated double bounds = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::PackedDoubleParser(_internal_mutable_bounds(), ptr, ctx);
          CHK_(ptr);
        } else if (static_cast<uint8_t>(tag) == 9) {
          _internal_add_bounds(::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<double>(ptr));
          ptr += sizeof(double);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* Distribution_ExplicitBuckets::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:google.api.servicecontrol.v1.Distribution.ExplicitBuckets)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // repeated double bounds = 1;
  if (this->_internal_bounds_size() > 0) {
    target = stream->WriteFixedPacked(1, _internal_bounds(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:google.api.servicecontrol.v1.Distribution.ExplicitBuckets)
  return target;
}

size_t Distribution_ExplicitBuckets::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:google.api.servicecontrol.v1.Distribution.ExplicitBuckets)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated double bounds = 1;
  {
    unsigned int count = static_cast<unsigned int>(this->_internal_bounds_size());
    size_t data_size = 8UL * count;
    if (data_size > 0) {
      total_size += 1 +
        ::_pbi::WireFormatLite::Int32Size(static_cast<int32_t>(data_size));
    }
    total_size += data_size;
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData Distribution_ExplicitBuckets::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    Distribution_ExplicitBuckets::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*Distribution_ExplicitBuckets::GetClassData() const { return &_class_data_; }


void Distribution_ExplicitBuckets::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<Distribution_ExplicitBuckets*>(&to_msg);
  auto& from = static_cast<const Distribution_ExplicitBuckets&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:google.api.servicecontrol.v1.Distribution.ExplicitBuckets)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_impl_.bounds_.MergeFrom(from._impl_.bounds_);
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void Distribution_ExplicitBuckets::CopyFrom(const Distribution_ExplicitBuckets& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:google.api.servicecontrol.v1.Distribution.ExplicitBuckets)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Distribution_ExplicitBuckets::IsInitialized() const {
  return true;
}

void Distribution_ExplicitBuckets::InternalSwap(Distribution_ExplicitBuckets* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  _impl_.bounds_.InternalSwap(&other->_impl_.bounds_);
}

::PROTOBUF_NAMESPACE_ID::Metadata Distribution_ExplicitBuckets::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_google_2fapi_2fservicecontrol_2fv1_2fdistribution_2eproto_getter, &descriptor_table_google_2fapi_2fservicecontrol_2fv1_2fdistribution_2eproto_once,
      file_level_metadata_google_2fapi_2fservicecontrol_2fv1_2fdistribution_2eproto[2]);
}

// ===================================================================

class Distribution::_Internal {
 public:
  static const ::google::api::servicecontrol::v1::Distribution_LinearBuckets& linear_buckets(const Distribution* msg);
  static const ::google::api::servicecontrol::v1::Distribution_ExponentialBuckets& exponential_buckets(const Distribution* msg);
  static const ::google::api::servicecontrol::v1::Distribution_ExplicitBuckets& explicit_buckets(const Distribution* msg);
};

const ::google::api::servicecontrol::v1::Distribution_LinearBuckets&
Distribution::_Internal::linear_buckets(const Distribution* msg) {
  return *msg->_impl_.bucket_option_.linear_buckets_;
}
const ::google::api::servicecontrol::v1::Distribution_ExponentialBuckets&
Distribution::_Internal::exponential_buckets(const Distribution* msg) {
  return *msg->_impl_.bucket_option_.exponential_buckets_;
}
const ::google::api::servicecontrol::v1::Distribution_ExplicitBuckets&
Distribution::_Internal::explicit_buckets(const Distribution* msg) {
  return *msg->_impl_.bucket_option_.explicit_buckets_;
}
void Distribution::set_allocated_linear_buckets(::google::api::servicecontrol::v1::Distribution_LinearBuckets* linear_buckets) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  clear_bucket_option();
  if (linear_buckets) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
      ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(linear_buckets);
    if (message_arena != submessage_arena) {
      linear_buckets = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, linear_buckets, submessage_arena);
    }
    set_has_linear_buckets();
    _impl_.bucket_option_.linear_buckets_ = linear_buckets;
  }
  // @@protoc_insertion_point(field_set_allocated:google.api.servicecontrol.v1.Distribution.linear_buckets)
}
void Distribution::set_allocated_exponential_buckets(::google::api::servicecontrol::v1::Distribution_ExponentialBuckets* exponential_buckets) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  clear_bucket_option();
  if (exponential_buckets) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
      ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(exponential_buckets);
    if (message_arena != submessage_arena) {
      exponential_buckets = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, exponential_buckets, submessage_arena);
    }
    set_has_exponential_buckets();
    _impl_.bucket_option_.exponential_buckets_ = exponential_buckets;
  }
  // @@protoc_insertion_point(field_set_allocated:google.api.servicecontrol.v1.Distribution.exponential_buckets)
}
void Distribution::set_allocated_explicit_buckets(::google::api::servicecontrol::v1::Distribution_ExplicitBuckets* explicit_buckets) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  clear_bucket_option();
  if (explicit_buckets) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
      ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(explicit_buckets);
    if (message_arena != submessage_arena) {
      explicit_buckets = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, explicit_buckets, submessage_arena);
    }
    set_has_explicit_buckets();
    _impl_.bucket_option_.explicit_buckets_ = explicit_buckets;
  }
  // @@protoc_insertion_point(field_set_allocated:google.api.servicecontrol.v1.Distribution.explicit_buckets)
}
void Distribution::clear_exemplars() {
  _impl_.exemplars_.Clear();
}
Distribution::Distribution(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:google.api.servicecontrol.v1.Distribution)
}
Distribution::Distribution(const Distribution& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  Distribution* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.bucket_counts_){from._impl_.bucket_counts_}
    , /*decltype(_impl_._bucket_counts_cached_byte_size_)*/{0}
    , decltype(_impl_.exemplars_){from._impl_.exemplars_}
    , decltype(_impl_.count_){}
    , decltype(_impl_.mean_){}
    , decltype(_impl_.minimum_){}
    , decltype(_impl_.maximum_){}
    , decltype(_impl_.sum_of_squared_deviation_){}
    , decltype(_impl_.bucket_option_){}
    , /*decltype(_impl_._cached_size_)*/{}
    , /*decltype(_impl_._oneof_case_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::memcpy(&_impl_.count_, &from._impl_.count_,
    static_cast<size_t>(reinterpret_cast<char*>(&_impl_.sum_of_squared_deviation_) -
    reinterpret_cast<char*>(&_impl_.count_)) + sizeof(_impl_.sum_of_squared_deviation_));
  clear_has_bucket_option();
  switch (from.bucket_option_case()) {
    case kLinearBuckets: {
      _this->_internal_mutable_linear_buckets()->::google::api::servicecontrol::v1::Distribution_LinearBuckets::MergeFrom(
          from._internal_linear_buckets());
      break;
    }
    case kExponentialBuckets: {
      _this->_internal_mutable_exponential_buckets()->::google::api::servicecontrol::v1::Distribution_ExponentialBuckets::MergeFrom(
          from._internal_exponential_buckets());
      break;
    }
    case kExplicitBuckets: {
      _this->_internal_mutable_explicit_buckets()->::google::api::servicecontrol::v1::Distribution_ExplicitBuckets::MergeFrom(
          from._internal_explicit_buckets());
      break;
    }
    case BUCKET_OPTION_NOT_SET: {
      break;
    }
  }
  // @@protoc_insertion_point(copy_constructor:google.api.servicecontrol.v1.Distribution)
}

inline void Distribution::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.bucket_counts_){arena}
    , /*decltype(_impl_._bucket_counts_cached_byte_size_)*/{0}
    , decltype(_impl_.exemplars_){arena}
    , decltype(_impl_.count_){int64_t{0}}
    , decltype(_impl_.mean_){0}
    , decltype(_impl_.minimum_){0}
    , decltype(_impl_.maximum_){0}
    , decltype(_impl_.sum_of_squared_deviation_){0}
    , decltype(_impl_.bucket_option_){}
    , /*decltype(_impl_._cached_size_)*/{}
    , /*decltype(_impl_._oneof_case_)*/{}
  };
  clear_has_bucket_option();
}

Distribution::~Distribution() {
  // @@protoc_insertion_point(destructor:google.api.servicecontrol.v1.Distribution)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void Distribution::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.bucket_counts_.~RepeatedField();
  _impl_.exemplars_.~RepeatedPtrField();
  if (has_bucket_option()) {
    clear_bucket_option();
  }
}

void Distribution::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void Distribution::clear_bucket_option() {
// @@protoc_insertion_point(one_of_clear_start:google.api.servicecontrol.v1.Distribution)
  switch (bucket_option_case()) {
    case kLinearBuckets: {
      if (GetArenaForAllocation() == nullptr) {
        delete _impl_.bucket_option_.linear_buckets_;
      }
      break;
    }
    case kExponentialBuckets: {
      if (GetArenaForAllocation() == nullptr) {
        delete _impl_.bucket_option_.exponential_buckets_;
      }
      break;
    }
    case kExplicitBuckets: {
      if (GetArenaForAllocation() == nullptr) {
        delete _impl_.bucket_option_.explicit_buckets_;
      }
      break;
    }
    case BUCKET_OPTION_NOT_SET: {
      break;
    }
  }
  _impl_._oneof_case_[0] = BUCKET_OPTION_NOT_SET;
}


void Distribution::Clear() {
// @@protoc_insertion_point(message_clear_start:google.api.servicecontrol.v1.Distribution)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.bucket_counts_.Clear();
  _impl_.exemplars_.Clear();
  ::memset(&_impl_.count_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&_impl_.sum_of_squared_deviation_) -
      reinterpret_cast<char*>(&_impl_.count_)) + sizeof(_impl_.sum_of_squared_deviation_));
  clear_bucket_option();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* Distribution::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // int64 count = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          _impl_.count_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // double mean = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 17)) {
          _impl_.mean_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<double>(ptr);
          ptr += sizeof(double);
        } else
          goto handle_unusual;
        continue;
      // double minimum = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 25)) {
          _impl_.minimum_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<double>(ptr);
          ptr += sizeof(double);
        } else
          goto handle_unusual;
        continue;
      // double maximum = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 33)) {
          _impl_.maximum_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<double>(ptr);
          ptr += sizeof(double);
        } else
          goto handle_unusual;
        continue;
      // double sum_of_squared_deviation = 5;
      case 5:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 41)) {
          _impl_.sum_of_squared_deviation_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<double>(ptr);
          ptr += sizeof(double);
        } else
          goto handle_unusual;
        continue;
      // repeated int64 bucket_counts = 6;
      case 6:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 50)) {
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::PackedInt64Parser(_internal_mutable_bucket_counts(), ptr, ctx);
          CHK_(ptr);
        } else if (static_cast<uint8_t>(tag) == 48) {
          _internal_add_bucket_counts(::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr));
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // .google.api.servicecontrol.v1.Distribution.LinearBuckets linear_buckets = 7;
      case 7:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 58)) {
          ptr = ctx->ParseMessage(_internal_mutable_linear_buckets(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // .google.api.servicecontrol.v1.Distribution.ExponentialBuckets exponential_buckets = 8;
      case 8:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 66)) {
          ptr = ctx->ParseMessage(_internal_mutable_exponential_buckets(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // .google.api.servicecontrol.v1.Distribution.ExplicitBuckets explicit_buckets = 9;
      case 9:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 74)) {
          ptr = ctx->ParseMessage(_internal_mutable_explicit_buckets(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // repeated .google.api.Distribution.Exemplar exemplars = 10;
      case 10:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 82)) {
          ptr -= 1;
          do {
            ptr += 1;
            ptr = ctx->ParseMessage(_internal_add_exemplars(), ptr);
            CHK_(ptr);
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<82>(ptr));
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* Distribution::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:google.api.servicecontrol.v1.Distribution)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // int64 count = 1;
  if (this->_internal_count() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt64ToArray(1, this->_internal_count(), target);
  }

  // double mean = 2;
  static_assert(sizeof(uint64_t) == sizeof(double), "Code assumes uint64_t and double are the same size.");
  double tmp_mean = this->_internal_mean();
  uint64_t raw_mean;
  memcpy(&raw_mean, &tmp_mean, sizeof(tmp_mean));
  if (raw_mean != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteDoubleToArray(2, this->_internal_mean(), target);
  }

  // double minimum = 3;
  static_assert(sizeof(uint64_t) == sizeof(double), "Code assumes uint64_t and double are the same size.");
  double tmp_minimum = this->_internal_minimum();
  uint64_t raw_minimum;
  memcpy(&raw_minimum, &tmp_minimum, sizeof(tmp_minimum));
  if (raw_minimum != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteDoubleToArray(3, this->_internal_minimum(), target);
  }

  // double maximum = 4;
  static_assert(sizeof(uint64_t) == sizeof(double), "Code assumes uint64_t and double are the same size.");
  double tmp_maximum = this->_internal_maximum();
  uint64_t raw_maximum;
  memcpy(&raw_maximum, &tmp_maximum, sizeof(tmp_maximum));
  if (raw_maximum != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteDoubleToArray(4, this->_internal_maximum(), target);
  }

  // double sum_of_squared_deviation = 5;
  static_assert(sizeof(uint64_t) == sizeof(double), "Code assumes uint64_t and double are the same size.");
  double tmp_sum_of_squared_deviation = this->_internal_sum_of_squared_deviation();
  uint64_t raw_sum_of_squared_deviation;
  memcpy(&raw_sum_of_squared_deviation, &tmp_sum_of_squared_deviation, sizeof(tmp_sum_of_squared_deviation));
  if (raw_sum_of_squared_deviation != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteDoubleToArray(5, this->_internal_sum_of_squared_deviation(), target);
  }

  // repeated int64 bucket_counts = 6;
  {
    int byte_size = _impl_._bucket_counts_cached_byte_size_.load(std::memory_order_relaxed);
    if (byte_size > 0) {
      target = stream->WriteInt64Packed(
          6, _internal_bucket_counts(), byte_size, target);
    }
  }

  // .google.api.servicecontrol.v1.Distribution.LinearBuckets linear_buckets = 7;
  if (_internal_has_linear_buckets()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(7, _Internal::linear_buckets(this),
        _Internal::linear_buckets(this).GetCachedSize(), target, stream);
  }

  // .google.api.servicecontrol.v1.Distribution.ExponentialBuckets exponential_buckets = 8;
  if (_internal_has_exponential_buckets()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(8, _Internal::exponential_buckets(this),
        _Internal::exponential_buckets(this).GetCachedSize(), target, stream);
  }

  // .google.api.servicecontrol.v1.Distribution.ExplicitBuckets explicit_buckets = 9;
  if (_internal_has_explicit_buckets()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(9, _Internal::explicit_buckets(this),
        _Internal::explicit_buckets(this).GetCachedSize(), target, stream);
  }

  // repeated .google.api.Distribution.Exemplar exemplars = 10;
  for (unsigned i = 0,
      n = static_cast<unsigned>(this->_internal_exemplars_size()); i < n; i++) {
    const auto& repfield = this->_internal_exemplars(i);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
        InternalWriteMessage(10, repfield, repfield.GetCachedSize(), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:google.api.servicecontrol.v1.Distribution)
  return target;
}

size_t Distribution::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:google.api.servicecontrol.v1.Distribution)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated int64 bucket_counts = 6;
  {
    size_t data_size = ::_pbi::WireFormatLite::
      Int64Size(this->_impl_.bucket_counts_);
    if (data_size > 0) {
      total_size += 1 +
        ::_pbi::WireFormatLite::Int32Size(static_cast<int32_t>(data_size));
    }
    int cached_size = ::_pbi::ToCachedSize(data_size);
    _impl_._bucket_counts_cached_byte_size_.store(cached_size,
                                    std::memory_order_relaxed);
    total_size += data_size;
  }

  // repeated .google.api.Distribution.Exemplar exemplars = 10;
  total_size += 1UL * this->_internal_exemplars_size();
  for (const auto& msg : this->_impl_.exemplars_) {
    total_size +=
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(msg);
  }

  // int64 count = 1;
  if (this->_internal_count() != 0) {
    total_size += ::_pbi::WireFormatLite::Int64SizePlusOne(this->_internal_count());
  }

  // double mean = 2;
  static_assert(sizeof(uint64_t) == sizeof(double), "Code assumes uint64_t and double are the same size.");
  double tmp_mean = this->_internal_mean();
  uint64_t raw_mean;
  memcpy(&raw_mean, &tmp_mean, sizeof(tmp_mean));
  if (raw_mean != 0) {
    total_size += 1 + 8;
  }

  // double minimum = 3;
  static_assert(sizeof(uint64_t) == sizeof(double), "Code assumes uint64_t and double are the same size.");
  double tmp_minimum = this->_internal_minimum();
  uint64_t raw_minimum;
  memcpy(&raw_minimum, &tmp_minimum, sizeof(tmp_minimum));
  if (raw_minimum != 0) {
    total_size += 1 + 8;
  }

  // double maximum = 4;
  static_assert(sizeof(uint64_t) == sizeof(double), "Code assumes uint64_t and double are the same size.");
  double tmp_maximum = this->_internal_maximum();
  uint64_t raw_maximum;
  memcpy(&raw_maximum, &tmp_maximum, sizeof(tmp_maximum));
  if (raw_maximum != 0) {
    total_size += 1 + 8;
  }

  // double sum_of_squared_deviation = 5;
  static_assert(sizeof(uint64_t) == sizeof(double), "Code assumes uint64_t and double are the same size.");
  double tmp_sum_of_squared_deviation = this->_internal_sum_of_squared_deviation();
  uint64_t raw_sum_of_squared_deviation;
  memcpy(&raw_sum_of_squared_deviation, &tmp_sum_of_squared_deviation, sizeof(tmp_sum_of_squared_deviation));
  if (raw_sum_of_squared_deviation != 0) {
    total_size += 1 + 8;
  }

  switch (bucket_option_case()) {
    // .google.api.servicecontrol.v1.Distribution.LinearBuckets linear_buckets = 7;
    case kLinearBuckets: {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
          *_impl_.bucket_option_.linear_buckets_);
      break;
    }
    // .google.api.servicecontrol.v1.Distribution.ExponentialBuckets exponential_buckets = 8;
    case kExponentialBuckets: {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
          *_impl_.bucket_option_.exponential_buckets_);
      break;
    }
    // .google.api.servicecontrol.v1.Distribution.ExplicitBuckets explicit_buckets = 9;
    case kExplicitBuckets: {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
          *_impl_.bucket_option_.explicit_buckets_);
      break;
    }
    case BUCKET_OPTION_NOT_SET: {
      break;
    }
  }
  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData Distribution::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    Distribution::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*Distribution::GetClassData() const { return &_class_data_; }


void Distribution::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<Distribution*>(&to_msg);
  auto& from = static_cast<const Distribution&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:google.api.servicecontrol.v1.Distribution)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_impl_.bucket_counts_.MergeFrom(from._impl_.bucket_counts_);
  _this->_impl_.exemplars_.MergeFrom(from._impl_.exemplars_);
  if (from._internal_count() != 0) {
    _this->_internal_set_count(from._internal_count());
  }
  static_assert(sizeof(uint64_t) == sizeof(double), "Code assumes uint64_t and double are the same size.");
  double tmp_mean = from._internal_mean();
  uint64_t raw_mean;
  memcpy(&raw_mean, &tmp_mean, sizeof(tmp_mean));
  if (raw_mean != 0) {
    _this->_internal_set_mean(from._internal_mean());
  }
  static_assert(sizeof(uint64_t) == sizeof(double), "Code assumes uint64_t and double are the same size.");
  double tmp_minimum = from._internal_minimum();
  uint64_t raw_minimum;
  memcpy(&raw_minimum, &tmp_minimum, sizeof(tmp_minimum));
  if (raw_minimum != 0) {
    _this->_internal_set_minimum(from._internal_minimum());
  }
  static_assert(sizeof(uint64_t) == sizeof(double), "Code assumes uint64_t and double are the same size.");
  double tmp_maximum = from._internal_maximum();
  uint64_t raw_maximum;
  memcpy(&raw_maximum, &tmp_maximum, sizeof(tmp_maximum));
  if (raw_maximum != 0) {
    _this->_internal_set_maximum(from._internal_maximum());
  }
  static_assert(sizeof(uint64_t) == sizeof(double), "Code assumes uint64_t and double are the same size.");
  double tmp_sum_of_squared_deviation = from._internal_sum_of_squared_deviation();
  uint64_t raw_sum_of_squared_deviation;
  memcpy(&raw_sum_of_squared_deviation, &tmp_sum_of_squared_deviation, sizeof(tmp_sum_of_squared_deviation));
  if (raw_sum_of_squared_deviation != 0) {
    _this->_internal_set_sum_of_squared_deviation(from._internal_sum_of_squared_deviation());
  }
  switch (from.bucket_option_case()) {
    case kLinearBuckets: {
      _this->_internal_mutable_linear_buckets()->::google::api::servicecontrol::v1::Distribution_LinearBuckets::MergeFrom(
          from._internal_linear_buckets());
      break;
    }
    case kExponentialBuckets: {
      _this->_internal_mutable_exponential_buckets()->::google::api::servicecontrol::v1::Distribution_ExponentialBuckets::MergeFrom(
          from._internal_exponential_buckets());
      break;
    }
    case kExplicitBuckets: {
      _this->_internal_mutable_explicit_buckets()->::google::api::servicecontrol::v1::Distribution_ExplicitBuckets::MergeFrom(
          from._internal_explicit_buckets());
      break;
    }
    case BUCKET_OPTION_NOT_SET: {
      break;
    }
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void Distribution::CopyFrom(const Distribution& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:google.api.servicecontrol.v1.Distribution)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Distribution::IsInitialized() const {
  return true;
}

void Distribution::InternalSwap(Distribution* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  _impl_.bucket_counts_.InternalSwap(&other->_impl_.bucket_counts_);
  _impl_.exemplars_.InternalSwap(&other->_impl_.exemplars_);
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(Distribution, _impl_.sum_of_squared_deviation_)
      + sizeof(Distribution::_impl_.sum_of_squared_deviation_)
      - PROTOBUF_FIELD_OFFSET(Distribution, _impl_.count_)>(
          reinterpret_cast<char*>(&_impl_.count_),
          reinterpret_cast<char*>(&other->_impl_.count_));
  swap(_impl_.bucket_option_, other->_impl_.bucket_option_);
  swap(_impl_._oneof_case_[0], other->_impl_._oneof_case_[0]);
}

::PROTOBUF_NAMESPACE_ID::Metadata Distribution::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_google_2fapi_2fservicecontrol_2fv1_2fdistribution_2eproto_getter, &descriptor_table_google_2fapi_2fservicecontrol_2fv1_2fdistribution_2eproto_once,
      file_level_metadata_google_2fapi_2fservicecontrol_2fv1_2fdistribution_2eproto[3]);
}

// @@protoc_insertion_point(namespace_scope)
}  // namespace v1
}  // namespace servicecontrol
}  // namespace api
}  // namespace google
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::google::api::servicecontrol::v1::Distribution_LinearBuckets*
Arena::CreateMaybeMessage< ::google::api::servicecontrol::v1::Distribution_LinearBuckets >(Arena* arena) {
  return Arena::CreateMessageInternal< ::google::api::servicecontrol::v1::Distribution_LinearBuckets >(arena);
}
template<> PROTOBUF_NOINLINE ::google::api::servicecontrol::v1::Distribution_ExponentialBuckets*
Arena::CreateMaybeMessage< ::google::api::servicecontrol::v1::Distribution_ExponentialBuckets >(Arena* arena) {
  return Arena::CreateMessageInternal< ::google::api::servicecontrol::v1::Distribution_ExponentialBuckets >(arena);
}
template<> PROTOBUF_NOINLINE ::google::api::servicecontrol::v1::Distribution_ExplicitBuckets*
Arena::CreateMaybeMessage< ::google::api::servicecontrol::v1::Distribution_ExplicitBuckets >(Arena* arena) {
  return Arena::CreateMessageInternal< ::google::api::servicecontrol::v1::Distribution_ExplicitBuckets >(arena);
}
template<> PROTOBUF_NOINLINE ::google::api::servicecontrol::v1::Distribution*
Arena::CreateMaybeMessage< ::google::api::servicecontrol::v1::Distribution >(Arena* arena) {
  return Arena::CreateMessageInternal< ::google::api::servicecontrol::v1::Distribution >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
